embeddings {
  tensor_name: "embedding:0"
  metadata_path: "D:/py_workspace/TF_basic/projector/projector/metadata.tsv"
  sprite {
    image_path: "D:/py_workspace/TF_basic/projector/data/mnist_10k_sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
